name: Test and Deploy

on:
  push:
    branches:
      - append

jobs:
  # run-checks:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3

  #     - name: Install Make
  #       run: sudo apt-get install make -y

  #     - name: Setup Python 3.10
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"

  #     - name: Create env
  #       run: make create-environment

  #     - name: Install Requirements
  #       run: make requirements

  #     - name: Run Security Checks
  #       run: make security-test

  #     - name: Run Static Code Check
  #       run: make run-flake

  #     - name: Run Coverage Checks
  #       run: make check-coverage

  # run-unit-tests:
  #   runs-on: ubuntu-latest
  #   needs: run-checks
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3

  #     - name: Setup Python 3.10
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"

  #     - name: Create env
  #       run: make create-environment

  #     - name: Install Requirements
  #       run: make requirements

  #     - name: Run Unit Tests
  #       run: make unit-test

  deploy:
    runs-on: ubuntu-latest
    # needs: run-unit-tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
